config/routes.rb
Rails.application.routes.draw do

#  resources :destinations, :only => [] do 
#    member do
#      get :show
#      patch :update
#      get :edit
#      delete :destroy
#    end
#
#    collection do
#      get :index
#      get :new
#      post :create 
#    end
#  end

  resources :destinations do

    resources :to_do_items

  end
end

app/models/destination.rb
class Destination < ActiveRecord::Base
  validates :name, :presence => true

  has_many :to_do_items
end

app/models/to_do_item.rb
class ToDoItem < ActiveRecord::Base

  validates :title, :presence => true
  validates :location, :presence => true

  belongs_to :destination
  
  geocoded_by :geocode_input
  after_validation :geocode 

  def geocode_input
    "#{location}, #{destination.name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout 'main'
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

  before_filter :load_all_destinations, :only => :index

  before_filter :load_one_destination, :only => :show

  def index
    @destination = Destination.new
  end

  def create
    @destination = Destination.new(allowed_params)
    if @destination.save
      respond_to do |format|
        format.html { redirect_to destination_path(@destination), :notice => "Record Saved"}
        format.js 
      end

    else
      render :new
    end
  end

  private
  def allowed_params
    params.require(:destination).permit(:name, :image_url)
  end

  def load_all_destinations
    @destinations = Destination.all
  end

  def load_one_destination
    @destination = Destination.find(params[:id])
  end

end

app/controllers/to_do_items_controller.rb
class ToDoItemsController < ApplicationController

  def create
    @to_do_item = ToDoItem.new(allowed_params)
    #Could take the ID from the url
    # @to_do_item.destination_id = params[:destination_id]
    @to_do_item.save!
  end

  private
  def allowed_params
    params.require(:to_do_item).permit(:title, :description, :destination_id, :location)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper

  def make_to_do_item(destination)
    ToDoItem.new(:destination_id => destination.id)
  end

  def to_do_item_id(destination)
    "to-do-items-#{destination.id}"
  end
end

app/helpers/to_do_items_helper.rb
module ToDoItemsHelper
end

app/views/destinations/_destination.html.erb
<div class="destination-wrap">

  <h3><%= destination.name %></h3>
  <img class="img-destination" src="<%= destination.image_url %>"/>

  <div id="<%= to_do_item_id(destination) %>">
    <%= render destination.to_do_items %>
  </div>

  <div class="to-do-item-form">
    <%= form_for make_to_do_item(destination), url: destination_to_do_items_path( destination ), :remote => true do |f| %>

      <%= field_set_tag do %>
      <%= f.label :title %>
    <%= f.text_field :title %>
  <% end %>

    <%= field_set_tag do %>
      <%= f.label :description %>
    <%= f.text_field :description %>
  <% end %>

    <%= field_set_tag do %>
      <%= f.label :location %>
    <%= f.text_field :location %>
  <% end %>

    <%= f.hidden_field :destination_id %>

    <%= f.submit "Create To Do Item" %>

  <% end %>
  </div>
</div>

app/views/destinations/create.js.erb
// This is what we were previously doing in the success callback in the destinations.js
$('#destinations').append("<%= j(render @destination) %>");

//("<#%= j(render :partial => 'destinations/destination', :locals => { :destinations => @destination }) %>");

  // (render @destination) <- this is a short version of the partial in ruby

app/views/destinations/index.html.erb
<div id="bucket_list">

  <div id="destinations">
    <% @destinations.each do |destination| %>
      <%= render :partial => "destinations/destination", :locals => { :destination => destination } %>
      <% end %>
  </div>

  <div class="add-destination">
    <%= link_to "Add Destination", "#"%>
  </div>

  <div class="add-todo">
    <%= link_to "Add To Do Item ", "#"%>
  </div>

  <div class="modal"> 
    <%= form_for @destination, :remote => true do |f|  %>
      <%= field_set_tag do %>
      <%= f.label :name %>
    <%= f.text_field :name %>
  <% end %>

    <%= field_set_tag do %>
      <%= f.label :image_url,"Image Url"%>
      <%= f.text_field :image_url %>
  <% end %>

    <%= f.submit "Create Destination" %>
  <% end %>
</div>

  </div>
</div>

<section id="map-canvas">
</section>

app/views/destinations/show.html.erb
<div class="show-destination">
  <h3><%= render @destination %></h3>
</div>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bucketlist</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD5gbcRXkRZevKNDz-GNeN1V-KtSjbgPiA&sensor=FALSE">
  </script>
</head>
  <body>
    <div id="wrapper">
      <div id="section">
        <h1>Travel Bucketlist</h1>

        <%= yield %>

      </div>
    </div>
  </body>
</html>

app/views/to_do_items/_to_do_item.hmtl.erb
<div class="to-do-item-title">
  <h3><%= to_do_item.title %></h3>
</div>

app/views/to_do_items/_to_do_item.html.erb
<div class="to-do-item-title">
  <h3><%= to_do_item.title %></h3>
</div>

app/views/to_do_items/create.js.erb
$('#to-do-items-<%=@to_do_item.destination.id%>').append("<%= j ( render @to_do_item ) %>");

addMarker(<%= @to_do_item.latitude %>, <%= @to_do_item.longitude %> );